#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tello-cv','console_scripts','circle_tracker_node'
__requires__ = 'tello-cv'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tello-cv', 'console_scripts', 'circle_tracker_node')()
    )
